[package]
name = "relegram"
version = "0.1.0"
authors = ["Ilya Titkov <ilya@titkov.me>"]

[dependencies]
hyper = "0.12"
hyper-tls = "0.3"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
chrono = "0.4"
futures  = "0.1"
